name: setup
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Setup
        run: make setup
      - name: Start
        run: make start
      - name: Testing
        run: make test
      - name: linting
        run: make lint
